name: swim
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=2.19.0-46.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  intl: ^0.17.0
  cached_network_image: ^3.2.1
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - asset/icon/
    - asset/image/
    - asset/image/2.0x/
    - asset/image/3.0x/
  
  fonts:
    - family: NewYork
      fonts:
        - asset: asset/font/NewYork/NewYork-400-regular.otf
        - asset: asset/font/NewYork/NewYork-600-bold.ttf
    - family: SpoqaHanSansNeo
      fonts:
        - asset: asset/font/SpoqaHanSansNeo_TTF_subset/SpoqaHanSansNeo-100-Thin.ttf
        - asset: asset/font/SpoqaHanSansNeo_TTF_subset/SpoqaHanSansNeo-300-Light.ttf
        - asset: asset/font/SpoqaHanSansNeo_TTF_subset/SpoqaHanSansNeo-400-Regular.ttf
        - asset: asset/font/SpoqaHanSansNeo_TTF_subset/SpoqaHanSansNeo-500-Medium.ttf
        - asset: asset/font/SpoqaHanSansNeo_TTF_subset/SpoqaHanSansNeo-700-Bold.ttf

flutter_intl:
  enabled: true
  arb_dir: lib/presentation/theme/lang/l10n
  output_dir: lib/presentation/theme/lang/generated